import { SUMMIT_COPY } from './ascent.config'
import type { SummitStone } from './data/types'
import { GROUND_Y, PEAK, pointOnTrail, RIDGE_POINTS, TRAIL_D } from './trailPath'

interface Props {
  year: number
  /** 0–1 of the calendar year elapsed — how much of the trail is behind you. */
  progress: number
  stones: SummitStone[]
  selectedId: string | null
  onSelect: (id: string | null) => void
}

const W = 600
const H = 320

/**
 * THE TRAIL — the year, drawn.
 *
 * Two things move on it, and only two. The lit stretch follows the CALENDAR: it
 * reaches the peak on 31 December whether the year held four hundred entries or
 * four. The stones follow the writer's life: one appears when an ask is met by a
 * later moment, which is an event, not an achievement. Neither is a progress bar
 * — nothing here can be filled faster by writing more, and that is the line that
 * keeps a memorial from becoming a streak.
 *
 * The mountain used to be decoration with a dotted line drawn on it and nothing
 * on the line. The stones were generated by every yearly rollup and rendered
 * nowhere.
 */
export function SummitTrail({ year, progress, stones, selectedId, onSelect }: Props) {
  const sealed = progress >= 1
  const lit = Math.min(1, Math.max(0, progress))

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      className="ascent-mountain"
      role="img"
      aria-label={
        stones.length > 0
          ? `The year ${year} — the trail climbed so far, with ${stones.length} ${stones.length === 1 ? 'stone' : 'stones'} set along it`
          : `The year ${year} — the trail climbed so far`
      }
    >
      <defs>
        <linearGradient id="ascent-rock" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="var(--ascent-rock-top)" />
          <stop offset="100%" stopColor="var(--ascent-rock-bottom)" />
        </linearGradient>
        <radialGradient id="ascent-peakglow" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="var(--ascent-gold-soft)" stopOpacity="0.55" />
          <stop offset="100%" stopColor="var(--ascent-gold-soft)" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="ascent-stoneglow" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="var(--ascent-gold-soft)" stopOpacity="0.5" />
          <stop offset="100%" stopColor="var(--ascent-gold-soft)" stopOpacity="0" />
        </radialGradient>
      </defs>

      <polygon points={RIDGE_POINTS} fill="url(#ascent-rock)" />

      {/* The whole year, unwalked — faint, and always the full path, so the trail
          is the shape of the year rather than a bar that fills. */}
      <path
        d={TRAIL_D}
        fill="none"
        stroke="var(--ascent-trail)"
        strokeWidth="1.5"
        strokeDasharray="2 5"
      />

      {/* The stretch behind you. `pathLength` re-scales the dash units to 0–1, so
          the lit fraction is exact without measuring the rendered geometry. */}
      <path
        d={TRAIL_D}
        className="ascent-trail"
        fill="none"
        stroke="var(--ascent-gold)"
        strokeOpacity="0.55"
        strokeWidth="1.6"
        strokeLinecap="round"
        pathLength={1}
        strokeDasharray={sealed ? 'none' : `${lit} 1`}
      />

      {/* The peak's own opacity rides on a WRAPPING group, not on the circles:
          `ascent-breathe` animates opacity, and an animation beats an inline
          attribute — so setting it on the circle lit the summit fully in March.
          Group opacity multiplies with the child's, which keeps the breathing. */}
      <g opacity={sealed ? 1 : 0.14 + 0.3 * lit}>
        <circle cx={PEAK[0]} cy={PEAK[1]} r="34" fill="url(#ascent-peakglow)" className="ascent-peak-glow" />
        <circle
          cx={PEAK[0]}
          cy={PEAK[1]}
          r="5"
          fill="var(--ascent-peak)"
          className={sealed ? 'ascent-peak-lit' : undefined}
        />
      </g>

      {stones.map((s, i) => {
        const at = pointOnTrail(s.position)
        const on = selectedId === s.id
        return (
          <g
            key={s.id}
            className="ascent-stone-g"
            style={{ animationDelay: `${0.5 + i * 0.12}s` }}
            role="button"
            tabIndex={0}
            aria-label={SUMMIT_COPY.stoneLabel(s.later.dateLabel)}
            aria-pressed={on}
            onClick={() => onSelect(on ? null : s.id)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault()
                onSelect(on ? null : s.id)
              }
            }}
          >
            {/* A generous transparent target: the cairn itself is 6px of rock. */}
            <circle cx={at.x} cy={at.y} r="16" fill="transparent" />
            {/* `ascent-ring` animates opacity, and an animation beats an inline
                attribute — so the open state stops the breathing in CSS rather
                than trying to out-set it here. */}
            <circle
              cx={at.x}
              cy={at.y}
              r="12"
              fill="url(#ascent-stoneglow)"
              className={on ? 'ascent-stone-ring is-open' : 'ascent-stone-ring'}
            />
            <circle cx={at.x} cy={at.y - 5.4} r="1.9" fill="var(--ascent-peak)" className="ascent-stone-dot" />
            <circle cx={at.x - 1.5} cy={at.y - 2.1} r="2.4" fill="var(--ascent-gold)" />
            <circle cx={at.x + 1.3} cy={at.y + 1.4} r="3" fill="var(--ascent-gold-soft)" opacity="0.75" />
          </g>
        )
      })}

      {/* The ground line, so the trail plainly starts somewhere. */}
      <line
        x1="40"
        y1={GROUND_Y}
        x2="560"
        y2={GROUND_Y}
        stroke="var(--ascent-trail)"
        strokeWidth="0.75"
        opacity="0.5"
      />
    </svg>
  )
}
