/**
 * GROWTH — the passive, backward-measured dimension.
 *
 * Nothing here is generated by this file and nothing is authored by the user: the
 * synthesis pass already writes every field it reads (`gain`, `gapWatch`,
 * `gainEvidence` at the month; `ebenezer` + `tensions` at the quarter;
 * `throughline` + `stones` at the year). Until now the client loaded three of the
 * four tiers and rendered four of ~fourteen reflection fields, so this content
 * was synthesized, stored, and never shown. This adapter is pure surfacing.
 *
 * Two guardrails are enforced HERE rather than trusted to the model:
 *
 *  1. NO PRIOR-PERIOD CLAIM. Every synthesis tier reads only its own period's
 *     children, so movement is measured ACROSS a period (start-of-period self vs.
 *     end-of-period self), never AGAINST the one before it. `acrossLabel` says
 *     "April", never "vs. March".
 *  2. NO UNGROUNDED PROSE AT THE HILLSIDE. A gain claim with no verbatim excerpt
 *     under it is dropped — the Gain lens without evidence is just flattery.
 *
 * The VALLEY has no growth block at all (the seam passes null): a week is too
 * close to see change in, which is the same reason the Valley interprets nothing.
 */

import type { EbenezerPair, Excerpt, Rollup, Tension } from '@/lib/insights'
import type { GrowthData, GrowthEvidence, GrowthPair, GrowthTension } from './types'
import { fmtDay } from './words'

/** How many excerpts can stand under the movement prose before it reads as a list. */
const MAX_EVIDENCE = 3
/** THEN/NOW pairs shown at once — the atom is the pair, not the pile. */
const MAX_PAIRS = 3
const MAX_TENSIONS = 3

function toEvidence(e: Excerpt | undefined): GrowthEvidence | null {
  if (!e || !e.entry_id || !e.date || !e.text?.trim()) return null
  return { entryId: e.entry_id, date: e.date, dateLabel: fmtDay(e.date), text: e.text.trim() }
}

/** A pair only stands if BOTH sides are real and the "now" genuinely follows the
 *  "then" — a reversed or same-day pair isn't a movement, it's a coincidence. */
function toPair(p: EbenezerPair, i: number): GrowthPair | null {
  const then = toEvidence(p.ask)
  const now = toEvidence(p.later)
  if (!then || !now) return null
  if (now.date <= then.date) return null
  return { id: p.id || `pair-${i}`, then, now }
}

function toTension(t: Tension, i: number): GrowthTension | null {
  const thread = t.thread?.trim()
  const question = t.question?.trim()
  if (!thread || !question) return null
  return { id: t.id || `tension-${i}`, thread, question }
}

function prose(lines: string[] | undefined): string[] {
  return (lines ?? []).map((l) => l.trim()).filter(Boolean)
}

/** The calendar month a monthly rollup covers ("April 2026"). */
function monthLabel(r: Rollup): string {
  return new Date(`${r.period_start}T00:00:00Z`).toLocaleDateString(undefined, {
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  })
}

/**
 * HILLSIDE — how you moved across the month, plus the Gap reflex to watch.
 * Reads `reflection.gain` / `gainEvidence` / `gapWatch` off the latest monthly.
 * Returns null when the prose is missing OR unevidenced (guardrail 2).
 */
export function monthGrowth(monthly: Rollup | undefined): GrowthData | null {
  if (!monthly) return null
  const r = monthly.payload.reflection
  const movement = prose(r?.gain)
  const evidence = (r?.gainEvidence ?? [])
    .map(toEvidence)
    .filter((e): e is GrowthEvidence => e !== null)
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(0, MAX_EVIDENCE)
  if (movement.length === 0 || evidence.length === 0) return null

  const gapWatch = r?.gapWatch?.trim()
  return {
    resolution: 'month',
    acrossLabel: monthLabel(monthly),
    movement,
    evidence,
    pairs: [],
    tensions: [],
    gapWatch: gapWatch ? gapWatch : null,
  }
}

/**
 * RIDGE — what you keep circling, handed back as questions, over the earlier-ask /
 * later-moment pairs. Reads the QUARTERLY rollup, a tier the client has never
 * loaded (the cron writes one on the 1st of each quarter). Prose is deliberately
 * omitted here: at the Ridge the app asks and never answers.
 */
export function quarterGrowth(quarterly: Rollup | undefined): GrowthData | null {
  if (!quarterly) return null
  const r = quarterly.payload.reflection
  const pairs = (r?.ebenezer ?? [])
    .map(toPair)
    .filter((p): p is GrowthPair => p !== null)
    .slice(0, MAX_PAIRS)
  const tensions = (r?.tensions ?? [])
    .map(toTension)
    .filter((t): t is GrowthTension => t !== null)
    .slice(0, MAX_TENSIONS)
  if (pairs.length === 0 && tensions.length === 0) return null

  return {
    resolution: 'quarter',
    acrossLabel: null,
    movement: [],
    evidence: [],
    pairs,
    tensions,
    gapWatch: null,
  }
}

/**
 * SUMMIT — who you were at the start of the year and who you are at the end, over
 * the stones (the year's strongest ask → later-moment pairings). The throughline
 * is the one place the app speaks at length, and only because the user climbed
 * this far to hear it.
 */
export function yearGrowth(yearly: Rollup | undefined): GrowthData | null {
  if (!yearly) return null
  const r = yearly.payload.reflection
  const movement = prose(r?.throughline)
  const pairs = (r?.stones ?? [])
    .map(toPair)
    .filter((p): p is GrowthPair => p !== null)
    .slice(0, MAX_PAIRS)
  if (movement.length === 0 && pairs.length === 0) return null

  return {
    resolution: 'year',
    acrossLabel: String(new Date(`${yearly.period_start}T00:00:00Z`).getUTCFullYear()),
    movement,
    evidence: [],
    pairs,
    tensions: [],
    gapWatch: null,
  }
}
